### ISSUE TITLE
robots.txt: 'str' object has no attribute '_meta'

### ISSUE THREAD

**Issue by julen** [evernote/pootle#24]
This exception randomly happens on the production server when trying to access the *robots.txt* view.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.6/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/l10n/pootle/pootle/apps/pootle_app/views/index/robots.py", line 26, in view
    langcodes = [language.code for language in Language.objects.iterator()]
  File "/usr/local/lib/python2.6/dist-packages/django/db/models/query.py", line 290, in iterator
    requested=requested, only_load=only_load)
  File "/usr/local/lib/python2.6/dist-packages/django/db/models/query.py", line 1341, in get_klass_info
    requested=next, only_load=only_load)
  File "/usr/local/lib/python2.6/dist-packages/django/db/models/query.py", line 1328, in get_klass_info
    field_count = len(klass._meta.fields)
AttributeError: 'str' object has no attribute '_meta'
```

**Comment by julen** [comment]
Closing as this has been migrated over.
